name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: install dep
      run: sudo apt-get update && sudo apt-get -y install clang meson git ninja-build
    - name: Build
      run: CC=clang meson build
    - name: Compile
      run: CC=clang ninja -C build
    - name: Test
      run: CC=clang ninja -C build test -v -d stats -d explain
